language: php

before_script:
  - git clone https://github.com/mkoppanen/php-zmq.git
  - sh -c "cd php-zmq && phpize && ./configure && make --silent && sudo make install"
  - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install --dev --prefer-source

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - vendor/bin/phpunit
